name: liqkit_ui_example
description: Minimal example showing how to import liqkit_ui.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  liqkit_ui:
    path: ..
