// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: tooling/gen/snippet_manifest.json
// Regenerate: melos run docs:gen:routes

export interface SnippetRoute {
  readonly component: string;
  readonly variant: string;
  readonly displayName: string;
  readonly path: string;
}

export const SNIPPET_ROUTES = {
  'accordion/default': { component: 'accordion', variant: 'default', displayName: "Default", path: '/accordion/default' },
  'accordion/multiple': { component: 'accordion', variant: 'multiple', displayName: "Multiple", path: '/accordion/multiple' },
  'accordion/single': { component: 'accordion', variant: 'single', displayName: "Single", path: '/accordion/single' },
  'action-sheet/default': { component: 'action-sheet', variant: 'default', displayName: "Default", path: '/action-sheet/default' },
  'action-sheet/with-cancel': { component: 'action-sheet', variant: 'with-cancel', displayName: "With Cancel", path: '/action-sheet/with-cancel' },
  'activity-view/default': { component: 'activity-view', variant: 'default', displayName: "Default", path: '/activity-view/default' },
  'alert/destructive': { component: 'alert', variant: 'destructive', displayName: "Destructive", path: '/alert/destructive' },
  'alert/side-by-side': { component: 'alert', variant: 'side-by-side', displayName: "Side by Side", path: '/alert/side-by-side' },
  'alert/stacked': { component: 'alert', variant: 'stacked', displayName: "Stacked", path: '/alert/stacked' },
  'app-icon/default': { component: 'app-icon', variant: 'default', displayName: "Default", path: '/app-icon/default' },
  'app-icon/with-badge': { component: 'app-icon', variant: 'with-badge', displayName: "With Badge", path: '/app-icon/with-badge' },
  'app-icon/with-caption': { component: 'app-icon', variant: 'with-caption', displayName: "With Caption", path: '/app-icon/with-caption' },
  'avatar/group': { component: 'avatar', variant: 'group', displayName: "Group", path: '/avatar/group' },
  'avatar/image': { component: 'avatar', variant: 'image', displayName: "Image", path: '/avatar/image' },
  'avatar/initials': { component: 'avatar', variant: 'initials', displayName: "Initials", path: '/avatar/initials' },
  'badge/counter': { component: 'badge', variant: 'counter', displayName: "Counter", path: '/badge/counter' },
  'badge/dot': { component: 'badge', variant: 'dot', displayName: "Dot", path: '/badge/dot' },
  'badge/status': { component: 'badge', variant: 'status', displayName: "Status", path: '/badge/status' },
  'bezel/no-island': { component: 'bezel', variant: 'no-island', displayName: "No Island", path: '/bezel/no-island' },
  'bezel/with-island': { component: 'bezel', variant: 'with-island', displayName: "With Island", path: '/bezel/with-island' },
  'breadcrumb/default': { component: 'breadcrumb', variant: 'default', displayName: "Default", path: '/breadcrumb/default' },
  'breadcrumb/with-separator': { component: 'breadcrumb', variant: 'with-separator', displayName: "With separator", path: '/breadcrumb/with-separator' },
  'button/destructive': { component: 'button', variant: 'destructive', displayName: "Destructive", path: '/button/destructive' },
  'button/glass': { component: 'button', variant: 'glass', displayName: "Glass", path: '/button/glass' },
  'button/regular': { component: 'button', variant: 'regular', displayName: "Regular", path: '/button/regular' },
  'calendar/default': { component: 'calendar', variant: 'default', displayName: "Default", path: '/calendar/default' },
  'calendar/with-bounds': { component: 'calendar', variant: 'with-bounds', displayName: "With bounds", path: '/calendar/with-bounds' },
  'card/default': { component: 'card', variant: 'default', displayName: "Default", path: '/card/default' },
  'card/with-footer': { component: 'card', variant: 'with-footer', displayName: "With footer", path: '/card/with-footer' },
  'card/with-header': { component: 'card', variant: 'with-header', displayName: "With header", path: '/card/with-header' },
  'checkbox/checked': { component: 'checkbox', variant: 'checked', displayName: "Checked", path: '/checkbox/checked' },
  'checkbox/indeterminate': { component: 'checkbox', variant: 'indeterminate', displayName: "Indeterminate", path: '/checkbox/indeterminate' },
  'checkbox/unchecked': { component: 'checkbox', variant: 'unchecked', displayName: "Unchecked", path: '/checkbox/unchecked' },
  'chip/dismissible': { component: 'chip', variant: 'dismissible', displayName: "Dismissible", path: '/chip/dismissible' },
  'chip/group': { component: 'chip', variant: 'group', displayName: "Group", path: '/chip/group' },
  'chip/single': { component: 'chip', variant: 'single', displayName: "Single", path: '/chip/single' },
  'color-picker/grid': { component: 'color-picker', variant: 'grid', displayName: "Grid", path: '/color-picker/grid' },
  'color-picker/large': { component: 'color-picker', variant: 'large', displayName: "Large", path: '/color-picker/large' },
  'color-picker/small': { component: 'color-picker', variant: 'small', displayName: "Small", path: '/color-picker/small' },
  'colors/swatch-grid': { component: 'colors', variant: 'swatch-grid', displayName: "Swatch grid", path: '/colors/swatch-grid' },
  'combobox/default': { component: 'combobox', variant: 'default', displayName: "Default", path: '/combobox/default' },
  'combobox/preselected': { component: 'combobox', variant: 'preselected', displayName: "Preselected", path: '/combobox/preselected' },
  'command-palette/default': { component: 'command-palette', variant: 'default', displayName: "Default", path: '/command-palette/default' },
  'command-palette/sections': { component: 'command-palette', variant: 'sections', displayName: "Sections", path: '/command-palette/sections' },
  'context-menu/below-leading': { component: 'context-menu', variant: 'below-leading', displayName: "Below Leading", path: '/context-menu/below-leading' },
  'context-menu/below-trailing': { component: 'context-menu', variant: 'below-trailing', displayName: "Below Trailing", path: '/context-menu/below-trailing' },
  'context-menu/beside-leading': { component: 'context-menu', variant: 'beside-leading', displayName: "Beside Leading", path: '/context-menu/beside-leading' },
  'dialog/default': { component: 'dialog', variant: 'default', displayName: "Default", path: '/dialog/default' },
  'dialog/with-actions': { component: 'dialog', variant: 'with-actions', displayName: "With actions", path: '/dialog/with-actions' },
  'divider/horizontal': { component: 'divider', variant: 'horizontal', displayName: "Horizontal", path: '/divider/horizontal' },
  'divider/vertical': { component: 'divider', variant: 'vertical', displayName: "Vertical", path: '/divider/vertical' },
  'divider/with-label': { component: 'divider', variant: 'with-label', displayName: "With label", path: '/divider/with-label' },
  'drawer/left': { component: 'drawer', variant: 'left', displayName: "Left", path: '/drawer/left' },
  'drawer/right': { component: 'drawer', variant: 'right', displayName: "Right", path: '/drawer/right' },
  'empty-state/default': { component: 'empty-state', variant: 'default', displayName: "Default", path: '/empty-state/default' },
  'empty-state/with-cta': { component: 'empty-state', variant: 'with-cta', displayName: "With CTA", path: '/empty-state/with-cta' },
  'examples/item': { component: 'examples', variant: 'item', displayName: "Item", path: '/examples/item' },
  'examples/panel': { component: 'examples', variant: 'panel', displayName: "Panel", path: '/examples/panel' },
  'examples/section': { component: 'examples', variant: 'section', displayName: "Section", path: '/examples/section' },
  'face-id/fail': { component: 'face-id', variant: 'fail', displayName: "Fail", path: '/face-id/fail' },
  'face-id/scanning': { component: 'face-id', variant: 'scanning', displayName: "Scanning", path: '/face-id/scanning' },
  'face-id/success': { component: 'face-id', variant: 'success', displayName: "Success", path: '/face-id/success' },
  'keyboard/numbers': { component: 'keyboard', variant: 'numbers', displayName: "Numbers", path: '/keyboard/numbers' },
  'keyboard/qwerty': { component: 'keyboard', variant: 'qwerty', displayName: "QWERTY", path: '/keyboard/qwerty' },
  'kit-helpers/header': { component: 'kit-helpers', variant: 'header', displayName: "Header", path: '/kit-helpers/header' },
  'kit-helpers/mode-labels': { component: 'kit-helpers', variant: 'mode-labels', displayName: "Mode Labels", path: '/kit-helpers/mode-labels' },
  'kit-helpers/mode-pill': { component: 'kit-helpers', variant: 'mode-pill', displayName: "Mode Pill", path: '/kit-helpers/mode-pill' },
  'label/optional': { component: 'label', variant: 'optional', displayName: "Optional", path: '/label/optional' },
  'label/required': { component: 'label', variant: 'required', displayName: "Required", path: '/label/required' },
  'list/dark': { component: 'list', variant: 'dark', displayName: "Dark", path: '/list/dark' },
  'list/grouped': { component: 'list', variant: 'grouped', displayName: "Grouped", path: '/list/grouped' },
  'materials/dark': { component: 'materials', variant: 'dark', displayName: "Dark", path: '/materials/dark' },
  'materials/light': { component: 'materials', variant: 'light', displayName: "Light", path: '/materials/light' },
  'menu/default': { component: 'menu', variant: 'default', displayName: "Default", path: '/menu/default' },
  'menu/with-section': { component: 'menu', variant: 'with-section', displayName: "With Section", path: '/menu/with-section' },
  'notification/mail': { component: 'notification', variant: 'mail', displayName: "Mail", path: '/notification/mail' },
  'notification/reminders': { component: 'notification', variant: 'reminders', displayName: "Reminders", path: '/notification/reminders' },
  'number-field/default': { component: 'number-field', variant: 'default', displayName: "Default", path: '/number-field/default' },
  'number-field/no-buttons': { component: 'number-field', variant: 'no-buttons', displayName: "No buttons", path: '/number-field/no-buttons' },
  'number-field/with-suffix': { component: 'number-field', variant: 'with-suffix', displayName: "With suffix", path: '/number-field/with-suffix' },
  'otp/default': { component: 'otp', variant: 'default', displayName: "Default", path: '/otp/default' },
  'otp/four-digit': { component: 'otp', variant: 'four-digit', displayName: "Four digits", path: '/otp/four-digit' },
  'otp/obscure': { component: 'otp', variant: 'obscure', displayName: "Obscure", path: '/otp/obscure' },
  'page-controls/dark': { component: 'page-controls', variant: 'dark', displayName: "Dark", path: '/page-controls/dark' },
  'page-controls/light': { component: 'page-controls', variant: 'light', displayName: "Light", path: '/page-controls/light' },
  'pagination/compact': { component: 'pagination', variant: 'compact', displayName: "Compact", path: '/pagination/compact' },
  'pagination/default': { component: 'pagination', variant: 'default', displayName: "Default", path: '/pagination/default' },
  'picker/inline-calendar': { component: 'picker', variant: 'inline-calendar', displayName: "Inline Calendar", path: '/picker/inline-calendar' },
  'popover/bottom': { component: 'popover', variant: 'bottom', displayName: "Bottom", path: '/popover/bottom' },
  'popover/leading': { component: 'popover', variant: 'leading', displayName: "Leading", path: '/popover/leading' },
  'popover/top': { component: 'popover', variant: 'top', displayName: "Top", path: '/popover/top' },
  'popover/trailing': { component: 'popover', variant: 'trailing', displayName: "Trailing", path: '/popover/trailing' },
  'popup-button/large': { component: 'popup-button', variant: 'large', displayName: "Large", path: '/popup-button/large' },
  'popup-button/regular': { component: 'popup-button', variant: 'regular', displayName: "Regular", path: '/popup-button/regular' },
  'progress/linear': { component: 'progress', variant: 'linear', displayName: "Linear", path: '/progress/linear' },
  'progress/spinner': { component: 'progress', variant: 'spinner', displayName: "Spinner", path: '/progress/spinner' },
  'radio/group': { component: 'radio', variant: 'group', displayName: "Group", path: '/radio/group' },
  'radio/single': { component: 'radio', variant: 'single', displayName: "Single", path: '/radio/single' },
  'segmented/four': { component: 'segmented', variant: 'four', displayName: "Four Segments", path: '/segmented/four' },
  'segmented/three': { component: 'segmented', variant: 'three', displayName: "Three Segments", path: '/segmented/three' },
  'segmented/two': { component: 'segmented', variant: 'two', displayName: "Two Segments", path: '/segmented/two' },
  'sheet/full-screen': { component: 'sheet', variant: 'full-screen', displayName: "Full Screen", path: '/sheet/full-screen' },
  'sheet/inspector': { component: 'sheet', variant: 'inspector', displayName: "Inspector", path: '/sheet/inspector' },
  'sheet/stacked': { component: 'sheet', variant: 'stacked', displayName: "Stacked", path: '/sheet/stacked' },
  'sidebar/default': { component: 'sidebar', variant: 'default', displayName: "Default", path: '/sidebar/default' },
  'sidebar/with-search': { component: 'sidebar', variant: 'with-search', displayName: "With Search", path: '/sidebar/with-search' },
  'skeleton/circle': { component: 'skeleton', variant: 'circle', displayName: "Circle", path: '/skeleton/circle' },
  'skeleton/rect': { component: 'skeleton', variant: 'rect', displayName: "Rectangle", path: '/skeleton/rect' },
  'skeleton/text': { component: 'skeleton', variant: 'text', displayName: "Text", path: '/skeleton/text' },
  'slider/dark': { component: 'slider', variant: 'dark', displayName: "Dark", path: '/slider/dark' },
  'slider/default': { component: 'slider', variant: 'default', displayName: "Default", path: '/slider/default' },
  'status-bar/dark': { component: 'status-bar', variant: 'dark', displayName: "Dark", path: '/status-bar/dark' },
  'status-bar/light': { component: 'status-bar', variant: 'light', displayName: "Light", path: '/status-bar/light' },
  'stepper/default': { component: 'stepper', variant: 'default', displayName: "Default", path: '/stepper/default' },
  'stepper/disabled': { component: 'stepper', variant: 'disabled', displayName: "Disabled", path: '/stepper/disabled' },
  'system/action-pill': { component: 'system', variant: 'action-pill', displayName: "Action Pill", path: '/system/action-pill' },
  'system/home-indicator': { component: 'system', variant: 'home-indicator', displayName: "Home Indicator", path: '/system/home-indicator' },
  'system/toggle-dot': { component: 'system', variant: 'toggle-dot', displayName: "Toggle Dot", path: '/system/toggle-dot' },
  'tabs/icons': { component: 'tabs', variant: 'icons', displayName: "Icons only", path: '/tabs/icons' },
  'tabs/pill': { component: 'tabs', variant: 'pill', displayName: "Pill", path: '/tabs/pill' },
  'tabs/underline': { component: 'tabs', variant: 'underline', displayName: "Underline", path: '/tabs/underline' },
  'text-field/disabled': { component: 'text-field', variant: 'disabled', displayName: "Disabled", path: '/text-field/disabled' },
  'text-field/empty': { component: 'text-field', variant: 'empty', displayName: "Empty", path: '/text-field/empty' },
  'text-field/filled': { component: 'text-field', variant: 'filled', displayName: "Filled", path: '/text-field/filled' },
  'text-field/obscured': { component: 'text-field', variant: 'obscured', displayName: "Obscured", path: '/text-field/obscured' },
  'text-styles/accessibility': { component: 'text-styles', variant: 'accessibility', displayName: "Accessibility sizes", path: '/text-styles/accessibility' },
  'text-styles/dynamic': { component: 'text-styles', variant: 'dynamic', displayName: "Dynamic Type", path: '/text-styles/dynamic' },
  'time-picker/12-hour': { component: 'time-picker', variant: '12-hour', displayName: "12-hour", path: '/time-picker/12-hour' },
  'time-picker/24-hour': { component: 'time-picker', variant: '24-hour', displayName: "24-hour", path: '/time-picker/24-hour' },
  'time-picker/intervals': { component: 'time-picker', variant: 'intervals', displayName: "Intervals", path: '/time-picker/intervals' },
  'toast/error': { component: 'toast', variant: 'error', displayName: "Error", path: '/toast/error' },
  'toast/info': { component: 'toast', variant: 'info', displayName: "Info", path: '/toast/info' },
  'toast/success': { component: 'toast', variant: 'success', displayName: "Success", path: '/toast/success' },
  'toggle/disabled': { component: 'toggle', variant: 'disabled', displayName: "Disabled", path: '/toggle/disabled' },
  'toggle/off': { component: 'toggle', variant: 'off', displayName: "Off", path: '/toggle/off' },
  'toggle/on': { component: 'toggle', variant: 'on', displayName: "On", path: '/toggle/on' },
  'toolbar/actions': { component: 'toolbar', variant: 'actions', displayName: "Actions", path: '/toolbar/actions' },
  'toolbar/chips': { component: 'toolbar', variant: 'chips', displayName: "Chips", path: '/toolbar/chips' },
  'tooltip/bottom': { component: 'tooltip', variant: 'bottom', displayName: "Bottom", path: '/tooltip/bottom' },
  'tooltip/top': { component: 'tooltip', variant: 'top', displayName: "Top", path: '/tooltip/top' },
  'tooltip/with-arrow': { component: 'tooltip', variant: 'with-arrow', displayName: "With arrow", path: '/tooltip/with-arrow' },
  'top-bar/large-title': { component: 'top-bar', variant: 'large-title', displayName: "Large Title", path: '/top-bar/large-title' },
  'top-bar/with-title': { component: 'top-bar', variant: 'with-title', displayName: "With Title", path: '/top-bar/with-title' },
  'widget/extra-large': { component: 'widget', variant: 'extra-large', displayName: "Extra Large", path: '/widget/extra-large' },
  'widget/large': { component: 'widget', variant: 'large', displayName: "Large", path: '/widget/large' },
  'widget/medium': { component: 'widget', variant: 'medium', displayName: "Medium", path: '/widget/medium' },
  'widget/small': { component: 'widget', variant: 'small', displayName: "Small", path: '/widget/small' },
  'window/default': { component: 'window', variant: 'default', displayName: "Default", path: '/window/default' },
  'window/inactive-controls': { component: 'window', variant: 'inactive-controls', displayName: "Inactive Controls", path: '/window/inactive-controls' },
} as const satisfies Record<string, SnippetRoute>;

export type SnippetRouteKey = keyof typeof SNIPPET_ROUTES;
