// Audits packages/liqkit_ui_design_data/ against liqkit's RELEASE_INVENTORY.md.
//
// For every category in the inventory, checks the presence of:
//   - figma_artifacts/<category-slug>/  (canonical screenshots, design-context, variable-defs)
//   - rendered/<category-slug>.html
//   - rendered/source/<category-slug>.native.html
//   - rendered/source/<category-slug>.native.css
//   - rendered/fidelity-snapshots/<category-slug>.png  OR equivalent
//   - native/components/<category-slug>/  (final canonical bundle)
//
// Writes a per-category coverage table to stdout and to
// packages/liqkit_ui_design_data/AUDIT.md. Exit non-zero if any
// category is fully missing.

import 'dart:convert';
import 'dart:io';

const String _repoRel = 'packages/liqkit_ui_design_data';

/// Every category as enumerated in liqkit's RELEASE_INVENTORY.md.
/// Slugs are the kebab-case name used in liqkit's filesystem.
const Map<String, String> _categories = <String, String>{
  'examples': 'Examples',
  'colors': 'Colors',
  'materials': 'Materials',
  'text-styles': 'Text styles',
  'bezels': 'Bezels',
  'system': 'System',
  'action-sheets': 'Action sheets',
  'activity-views': 'Activity views',
  'alerts': 'Alerts',
  'app-icons': 'App icons',
  'buttons': 'Buttons',
  'color-pickers': 'Color pickers',
  'context-menu': 'Context menu',
  'empty-states': 'Empty states',
  'face-id': 'Face ID',
  'keyboards': 'Keyboards',
  'lists': 'Lists',
  'menu': 'Menu',
  'notifications': 'Notifications',
  'page-controls': 'Page controls',
  'pickers': 'Pickers',
  'popovers': 'Popovers',
  'popup-buttons': 'Popup buttons',
  'progress-indicators': 'Progress indicators',
  'segmented-controls': 'Segmented controls',
  'sheets': 'Sheets',
  'sidebars': 'Sidebars',
  'sliders': 'Sliders',
  'status-bars': 'Status bars',
  'steppers': 'Steppers',
  'top-bars': 'Top bars',
  'text-fields': 'Text fields',
  'toggles': 'Toggles',
  'toolbars': 'Toolbars',
  'widgets': 'Widgets',
  'windows': 'Windows',
  'kit-helpers': 'Kit helpers',
};

void main(List<String> args) {
  final repoRoot = _findRepoRoot();
  final root = Directory('${repoRoot.path}/$_repoRel');
  if (!root.existsSync()) {
    stderr.writeln('audit: $_repoRel does not exist.');
    exit(2);
  }

  final rows = <_Row>[];
  for (final entry in _categories.entries) {
    final slug = entry.key;
    final display = entry.value;
    rows.add(_audit(root, slug, display));
  }

  final missingCanonical = rows
      .where((r) => !r.figmaArtifactsPresent)
      .map((r) => r.slug)
      .toList();
  final missingRenderedHtml = rows
      .where((r) => !r.renderedHtml)
      .map((r) => r.slug)
      .toList();
  final missingNativeSource = rows
      .where((r) => !r.nativeHtmlSource || !r.nativeCssSource)
      .map((r) => r.slug)
      .toList();
  final missingFidelity = rows
      .where((r) => !r.fidelitySnapshot)
      .map((r) => r.slug)
      .toList();
  final missingNativeBundle = rows
      .where((r) => !r.nativeBundle)
      .map((r) => r.slug)
      .toList();

  // Write Markdown audit report.
  final buf = StringBuffer()
    ..writeln('# liqkit_ui_design_data audit')
    ..writeln()
    ..writeln('Generated by `tooling/scripts/audit_design_data.dart`.')
    ..writeln()
    ..writeln('## Per-category coverage')
    ..writeln()
    ..writeln(
      '| Slug | Display | Figma artifacts | Rendered HTML | Native HTML source | Native CSS source | Fidelity snapshot | Native bundle |',
    )
    ..writeln(
      '|---|---|---|---|---|---|---|---|',
    );
  for (final r in rows) {
    buf.writeln(
      '| `${r.slug}` | ${r.display} | ${_check(r.figmaArtifactsPresent)} | ${_check(r.renderedHtml)} | ${_check(r.nativeHtmlSource)} | ${_check(r.nativeCssSource)} | ${_check(r.fidelitySnapshot)} | ${_check(r.nativeBundle)} |',
    );
  }
  buf
    ..writeln()
    ..writeln('## Summary')
    ..writeln()
    ..writeln('- Categories total: ${_categories.length}')
    ..writeln('- Missing figma_artifacts: ${missingCanonical.length}')
    ..writeln('- Missing rendered HTML: ${missingRenderedHtml.length}')
    ..writeln('- Missing native source: ${missingNativeSource.length}')
    ..writeln('- Missing fidelity snapshot: ${missingFidelity.length}')
    ..writeln('- Missing native bundle: ${missingNativeBundle.length}')
    ..writeln();

  if (missingCanonical.isNotEmpty) {
    buf
      ..writeln('### Missing figma_artifacts')
      ..writeln(missingCanonical.map((s) => '- `$s`').join('\n'))
      ..writeln();
  }
  if (missingRenderedHtml.isNotEmpty) {
    buf
      ..writeln('### Missing rendered HTML')
      ..writeln(missingRenderedHtml.map((s) => '- `$s`').join('\n'))
      ..writeln();
  }
  if (missingNativeSource.isNotEmpty) {
    buf
      ..writeln('### Missing native source')
      ..writeln(missingNativeSource.map((s) => '- `$s`').join('\n'))
      ..writeln();
  }
  if (missingFidelity.isNotEmpty) {
    buf
      ..writeln('### Missing fidelity snapshot')
      ..writeln(missingFidelity.map((s) => '- `$s`').join('\n'))
      ..writeln();
  }
  if (missingNativeBundle.isNotEmpty) {
    buf
      ..writeln('### Missing native bundle')
      ..writeln(missingNativeBundle.map((s) => '- `$s`').join('\n'))
      ..writeln();
  }

  File('${root.path}/AUDIT.md').writeAsStringSync(buf.toString());

  stdout.writeln('audit: wrote ${root.path}/AUDIT.md');
  stdout.writeln('audit: ${rows.length} categories audited');
  stdout.writeln('audit: missing canonical figma_artifacts: ${missingCanonical.length}');
  stdout.writeln('audit: missing rendered HTML:            ${missingRenderedHtml.length}');
  stdout.writeln('audit: missing native source:            ${missingNativeSource.length}');
  stdout.writeln('audit: missing fidelity snapshot:        ${missingFidelity.length}');
  stdout.writeln('audit: missing native bundle:            ${missingNativeBundle.length}');

  // Also write a JSON manifest of audited slugs for the Playwright suite.
  final manifestPath = '${root.path}/manifests/audit.json';
  File(manifestPath).writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert(<String, Object>{
      'auditedAt': DateTime.now().toUtc().toIso8601String(),
      'categories': rows.map((r) => r.toJson()).toList(),
    }),
  );
  stdout.writeln('audit: wrote $manifestPath');

  // Hard-fail only if we have categories with NO evidence whatsoever.
  final critical = rows
      .where(
        (r) =>
            !r.figmaArtifactsPresent &&
            !r.renderedHtml &&
            !r.nativeBundle,
      )
      .toList();
  if (critical.isNotEmpty) {
    stderr.writeln(
      'audit: CRITICAL gaps in ${critical.length} categories (no evidence at all):',
    );
    for (final c in critical) {
      stderr.writeln('  - ${c.slug}');
    }
    exit(1);
  }
}

class _Row {
  _Row({
    required this.slug,
    required this.display,
    required this.figmaArtifactsPresent,
    required this.figmaArtifactsCount,
    required this.renderedHtml,
    required this.nativeHtmlSource,
    required this.nativeCssSource,
    required this.fidelitySnapshot,
    required this.nativeBundle,
  });

  final String slug;
  final String display;
  final bool figmaArtifactsPresent;
  final int figmaArtifactsCount;
  final bool renderedHtml;
  final bool nativeHtmlSource;
  final bool nativeCssSource;
  final bool fidelitySnapshot;
  final bool nativeBundle;

  Map<String, Object> toJson() => <String, Object>{
        'slug': slug,
        'display': display,
        'figmaArtifactsPresent': figmaArtifactsPresent,
        'figmaArtifactsCount': figmaArtifactsCount,
        'renderedHtml': renderedHtml,
        'nativeHtmlSource': nativeHtmlSource,
        'nativeCssSource': nativeCssSource,
        'fidelitySnapshot': fidelitySnapshot,
        'nativeBundle': nativeBundle,
      };
}

_Row _audit(Directory root, String slug, String display) {
  final figmaDir = Directory('${root.path}/figma_artifacts/$slug');
  final figmaArtifactsPresent = figmaDir.existsSync();
  final figmaArtifactsCount = figmaArtifactsPresent
      ? figmaDir
          .listSync()
          .whereType<File>()
          .where(
            (f) => f.path.endsWith('.png') ||
                f.path.endsWith('.txt') ||
                f.path.endsWith('.json'),
          )
          .length
      : 0;

  final renderedHtml =
      File('${root.path}/rendered/$slug.html').existsSync();
  final nativeHtmlSource = File(
    '${root.path}/rendered/source/$slug.native.html',
  ).existsSync();
  final nativeCssSource = File(
    '${root.path}/rendered/source/$slug.native.css',
  ).existsSync();

  // Fidelity snapshot may be either rendered/fidelity-snapshots/<slug>.png or
  // a per-category subdir.
  final fidelityFile =
      File('${root.path}/rendered/fidelity-snapshots/$slug.png');
  final fidelityDir =
      Directory('${root.path}/rendered/fidelity-snapshots/$slug');
  final fidelitySnapshot = fidelityFile.existsSync() || fidelityDir.existsSync();

  final nativeBundleHtml =
      File('${root.path}/native/components/$slug.html').existsSync();
  final nativeBundleCss =
      File('${root.path}/native/components/$slug.css').existsSync();
  final nativeBundle = nativeBundleHtml && nativeBundleCss;

  return _Row(
    slug: slug,
    display: display,
    figmaArtifactsPresent: figmaArtifactsPresent,
    figmaArtifactsCount: figmaArtifactsCount,
    renderedHtml: renderedHtml,
    nativeHtmlSource: nativeHtmlSource,
    nativeCssSource: nativeCssSource,
    fidelitySnapshot: fidelitySnapshot,
    nativeBundle: nativeBundle,
  );
}

String _check(bool ok) => ok ? '✓' : '✗';

Directory _findRepoRoot() {
  var dir = Directory.current;
  while (dir.parent.path != dir.path) {
    final pubspec = File('${dir.path}/pubspec.yaml');
    if (pubspec.existsSync() &&
        pubspec.readAsStringSync().contains('liqkit_ui_workspace')) {
      return dir;
    }
    dir = dir.parent;
  }
  throw StateError('Could not find liqkit_ui_workspace pubspec.yaml');
}
